name: test

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: master

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: latest

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test

      - name: Compute coverage
        run: npm run coverage

      - name: Publish coverage
        uses: coverallsapp/github-action@v2